dmglog.IncludeClientFile('cl_damagetab.lua')
dmglog.IncludeClientFile('vgui/cl_selection_panel.lua')
dmglog.IncludeClientFile('vgui/cl_dmglogs_view.lua')
dmglog.IncludeClientFile('vgui/cl_round_selection.lua')
dmglog.IncludeClientFile('vgui/cl_roles_view.lua')